### ISSUE TITLE
mean faces

### ISSUE THREAD

**Issue by ouwen18** [Exgc/OpenSR#2]
In the process of preprocessing LRS2, this script generates mouth Regions of Interest (ROIs) in ${lrs2}/video. It shards all the videos listed in ${lrs2}/file.list into ${nshard} portions and generates mouth ROIs for the ${rank}-th shard, where "rank" is an integer in the range [0, nshard-1]. Face detection and landmark prediction are performed using the Dlib library. 

The links to download the cnn_detector, face_detector, and mean_face can be found in the help message. However, it's not clear where to download the "mean_face," and further guidance is needed.

**Comment by Exgc** [comment]
Refer to: https://github.com/Exgc/OpenSR/blob/ea2dc5f9428e4ddf203fca6ea25ae36825583dda/opensr/preparation/align_mouth.py#L126
