### ISSUE TITLE
preval.txt

### ISSUE THREAD

**Issue by ouwen18** [Exgc/OpenSR#3]
I noticed the following step in the data preprocessing process: preval_fids = set([f'short-pretrain/{x.strip()}' for x in open(os.path.join(args.lrs2, 'preval.txt')).readlines()]). Could you please clarify what 'preval.txt' refers to? I couldn't find this file in my LRS2 dataset. Is it all the IDs from the previously processed 'short-pretrain

**Comment by Exgc** [comment]
This is the data used for validation when performing pre-training validation in other previous work, and contains 1000 pieces of data for validation. We have corrected the code in #https://github.com/Exgc/OpenSR/commit/05dc223752a5a372e80ab912b2007a3b30e33bc7 and can now use more data to get better results.
